version: '3.0'  
services:
  notary:
    image: corda/corda-zulu-java1.8-4.4
    container_name: notary
    ports:
      - "10003:10201"
      - "2000:2222"
    volumes:
      - ./build/nodes/Notary/node.conf:/etc/corda/node.conf
      - ./build/nodes/Notary/certificates:/opt/corda/certificates
      - ./build/nodes/Notary/persistence:/opt/corda/persistence
      - ./build/nodes/Notary/logs:/opt/corda/logs
      - ./build/nodes/shared/cordapps:/opt/corda/cordapps
      - ./build/nodes/shared/node-infos:/opt/corda/additional-node-infos
      - ./build/nodes/shared/network-parameters:/opt/corda/network-parameters
    partya:
      image: corda/corda-zulu-java1.8-4.4
      container_name: partya
      ports:
        - "10006:10201"
        - "2001:2222"
      volumes:
        - ./build/nodes/partya/node.conf:/etc/corda/node.conf
        - ./build/nodes/partya/certificates:/opt/corda/certificates
        - ./build/nodes/partya/persistence:/opt/corda/persistence
        - ./build/nodes/partya/logs:/opt/corda/logs
        - ./build/nodes/shared/cordapps:/opt/corda/cordapps
        - ./build/nodes/shared/node-infos:/opt/corda/additional-node-infos
        - ./build/nodes/shared/network-parameters:/opt/corda/network-parameters
    partyb:
      image: corda/corda-zulu-java1.8-4.4
      container_name: partyb
      ports:
        - "10009:10201"
        - "2002:2222"
      volumes:
        - ./build/nodes/partyb/node.conf:/etc/corda/node.conf
        - ./build/nodes/partyb/certificates:/opt/corda/certificates
        - ./build/nodes/partyb/persistence:/opt/corda/persistence
        - ./build/nodes/partyb/logs:/opt/corda/logs
        - ./build/nodes/shared/cordapps:/opt/corda/cordapps
        - ./build/nodes/shared/node-infos:/opt/corda/additional-node-infos
        - ./build/nodes/shared/network-parameters:/opt/corda/network-parameters
    partyc:
      image: corda/corda-zulu-java1.8-4.4
      container_name: partyc
      ports:
        - "10012:10201"
        - "2003:2222"
      volumes:
        - ./build/nodes/partyc/node.conf:/etc/corda/node.conf
        - ./build/nodes/partyc/certificates:/opt/corda/certificates
        - ./build/nodes/partyc/persistence:/opt/corda/persistence
        - ./build/nodes/partyc/logs:/opt/corda/logs
        - ./build/nodes/shared/cordapps:/opt/corda/cordapps
        - ./build/nodes/shared/node-infos:/opt/corda/additional-node-infos
        - ./build/nodes/shared/network-parameters:/opt/corda/network-parameters
  corda-postgres:
    container_name: corda-postgres
    image: postgres:14.2-alpine
    networks:
      - corda
    restart: always
    environment:
      - POSTGRES_USER=corda
      - POSTGRES_PASSWORD=corda
    ports:
      - 5439:5432
    volumes:
      - cordapostgres001:/var/lib/postgresql/data
volumes:
  cordapostgres001:
networks:
  corda: